//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public news()
        {
            this.ucomments = new HashSet<ucomment>();
        }
    
        public int nid { get; set; }
        public string news1 { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual category category { get; set; }
        public virtual nuser nuser { get; set; }
        public virtual ICollection<ucomment> ucomments { get; set; }
    }
}
