//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class nuser
    {
        public nuser()
        {
            this.news = new HashSet<news>();
        }
    
        public int uid { get; set; }
        public string uname { get; set; }
    
        public virtual ICollection<news> news { get; set; }
    }
}
