//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpro()
        {
            this.tblimages = new HashSet<tblimage>();
            this.tblorderdetails = new HashSet<tblorderdetail>();
        }
    
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<decimal> pprice { get; set; }
        public string pdetails { get; set; }
        public Nullable<int> cid { get; set; }
    
        public virtual tblcat tblcat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblimage> tblimages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorderdetail> tblorderdetails { get; set; }
    }
}
